---
- name: Tools
  become: True
  community.general.pacman:
    name: "{{ item }}"
    state: present
  with_items: "{{ packages_to_install }}"

- name: Install Python libraries
  become: True
  community.general.pipx:
    name: "{{ item }}"
  with_items: "{{ python_packages }}"
