---
- name: Tools
  become: True
  community.general.pacman:
    name: "{{ items }}"
    state: present
  with_items: "{{ packages_to_install }}"

- name: Install Python libraries
  become: True
  pip:
    name: "{{ item }}"
  with_items: "{{ python_packages }}"
