---
packages_to_install:
  - amass
  - asnmap
  - bind
  - bloodhound
  - bloodhound-python
  - burpsuite
  - crackmapexec
  - cupp
  - dirb
  - dirbuster
  - dnsenum
  - dnsrecon
  - eyewitness
  - feh
  - feroxbuster
  - ffuf
  - fierce
  - firefox
  - flameshot
  - ghidra
  - gnu-netcat
  - go
  - gobuster
  - hashcat
  - hashcat-utils
  - impacket
  - john
  - jq
  - metasploit
  - man-db
  - man-pages
  - net-tools
  - nikto
  - nmap
  - openldap
  - openresolv
  - openvpn
  - pandoc
  - proxychains-ng
  - puredns
  - python-pipx
  - python-pypykatz
  - python-shodan
  - responder
  - seclists
  - smbclient
  - smtp-user-enum
  - sqlmap
  - subfinder
  - tcpdump
  - thunar
  - tor-browser
  - tree
  - wfuzz
  - whois
  - wireguard-tools
  - wireshark-cli
  - wireshark-qt
  - xxd
  - zaproxy

python_packages:
  - pwntools
  - bbot
